package Courier.CourierService.Models;

// Generated Jan 15, 2014 9:14:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Log generated by hbm2java
 */
@Entity
@Table(name = "Log", catalog = "CourierDB")
public class Log implements java.io.Serializable {

	private Integer logId;
	private String event;
	private Date time;
	private String device;

	public Log() {
	}

	public Log(String event, Date time) {
		this.event = event;
		this.time = time;
	}

	public Log(String event, Date time, String device) {
		this.event = event;
		this.time = time;
		this.device = device;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "LogId", unique = true, nullable = false)
	public Integer getLogId() {
		return this.logId;
	}

	public void setLogId(Integer logId) {
		this.logId = logId;
	}

	@Column(name = "Event", nullable = false)
	public String getEvent() {
		return this.event;
	}

	public void setEvent(String event) {
		this.event = event;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Time", nullable = false, length = 19)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "Device", length = 75)
	public String getDevice() {
		return this.device;
	}

	public void setDevice(String device) {
		this.device = device;
	}

}
