package Courier.CourierService.Models;

// Generated Jan 15, 2014 9:14:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Route generated by hbm2java
 */
@Entity
@Table(name = "Route", catalog = "CourierDB")
public class Route implements java.io.Serializable {

	private Integer routeId;
	private String startPoint;
	private String endPoint;
	private Set<RouteInformation> routeInformations = new HashSet<RouteInformation>(
			0);

	public Route() {
	}

	public Route(String startPoint, String endPoint) {
		this.endPoint = endPoint;
		this.startPoint = startPoint;
	}

	public Route(String from, String to, Set<RouteInformation> routeInformations) {
		this.startPoint = from;
		this.endPoint = to;
		this.routeInformations = routeInformations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "RouteId", unique = true, nullable = false)
	public Integer getRouteId() {
		return this.routeId;
	}

	public void setRouteId(Integer routeId) {
		this.routeId = routeId;
	}

	@Column(name = "StartPoint")
	public String getStartPoint() {
		return this.startPoint;
	}

	public void setStartPoint(String startPoint) {
		this.startPoint = startPoint;
	}

	@Column(name = "EndPoint", nullable = false)
	public String getEndPoint() {
		return this.endPoint;
	}

	public void setEndPoint(String endPoint) {
		this.endPoint = endPoint;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "route")
	public Set<RouteInformation> getRouteInformations() {
		return this.routeInformations;
	}

	public void setRouteInformations(Set<RouteInformation> routeInformations) {
		this.routeInformations = routeInformations;
	}

}
