package Courier.CourierService.Models;

// Generated Jan 15, 2014 9:14:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.ccnx.android.ccnlib.JsonMessage;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "User", catalog = "CourierDB")
public class User extends JsonMessage implements java.io.Serializable {

	private Integer userId;
	private String login;
	private String password;
	private String email;
	private String type;
	private Set<RouteInformation> routeInformations = new HashSet<RouteInformation>(
			0);
	private Set<Car> cars = new HashSet<Car>(0);

	public User() {
	}

	public User(String login, String password, String email) {
		this.login = login;
		this.password = password;
		this.email = email;
	}

	public User(String login, String password, String email, String type,
			Set<RouteInformation> routeInformations, Set<Car> cars) {
		this.login = login;
		this.password = password;
		this.email = email;
		this.type = type;
		this.routeInformations = routeInformations;
		this.cars = cars;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "UserId", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "Login", nullable = false, length = 45)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "Password", nullable = false, length = 32)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "Email", nullable = false, length = 75)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Type", columnDefinition="enum('Kierownik', 'Kierowca')")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "user")
	public Set<RouteInformation> getRouteInformations() {
		return this.routeInformations;
	}

	public void setRouteInformations(Set<RouteInformation> routeInformations) {
		this.routeInformations = routeInformations;
	}

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "User_Car", catalog = "CourierDB", joinColumns = { @JoinColumn(name = "UserId", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "CarId", nullable = false, updatable = false) })
	public Set<Car> getCars() {
		return this.cars;
	}

	public void setCars(Set<Car> cars) {
		this.cars = cars;
	}

}
